# -*- coding: utf-8 -*-
"""stylegan2-ada Training/Transfer Learning

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11TEdCoOp7TXe4nQecGXQPQQETkA_ZS21
"""

!nvidia-smi

"""# Set Up Environment

1) Google Drive에 Mount를 진행함.

2) 필요 package install

3) 공식 StyleGAN2-ADA git clone
"""

try:
    from google.colab import drive
    drive.mount('/content/drive', force_remount=True)
    COLAB = True
    print("Note: using Google CoLab")
except:
    print("Note: not using Google CoLab")
    COLAB = False

!pip install torch==1.8.1 torchvision==0.9.1
!pip install ninja

!git clone https://github.com/NVlabs/stylegan2-ada-pytorch.git

"""# Find Your Files

Mount된 이미지 데이터 세트의 개수를 확인하고 압축을 해제함.

```
/content/drive/MyDrive/data
```

"""

!ls /content/drive/MyDrive/data/gan/images

!unzip -qq "/content/drive/MyDrive/data/gan/images/celeba_hq_15k.zip" -d "/content/drive/MyDrive/data/gan/images/celeba_hq_15k"

img_dir_name = "celeba_hq_15k"

import glob
import os

DIR = "/content/drive/MyDrive/data/gan/images/" + img_dir_name
print (len([name for name in os.listdir(DIR) if os.path.isfile(os.path.join(DIR, name))]))

"""# Convert Your Images

dataset_tool.py를 활용하여 활용하고자 하는 데이터 세트의 이미지 사이즈를 resize하고 Drive에 저장함.
"""

!rm -R /content/drive/MyDrive/data/gan/dataset/circuit/*

W, H = 256, 256

!python /content/stylegan2-ada-pytorch/dataset_tool.py --source /content/drive/MyDrive/data/gan/images/celeba_hq_15k/ --dest /content/drive/MyDrive/data/gan/dataset/circuit --width {W} --height {H}

"""# Training from scratch

처음부터 훈련시키거나 특정 위치의 pkl을 활용하여 훈련시키기 위한 코드
"""

import os

# Modify these to suit your needs
EXPERIMENTS = "/content/drive/MyDrive/data/gan/experiments"
DATA = "/content/drive/MyDrive/data/gan/dataset/circuit"
SNAP = 8

# Build the command and run it
cmd = f"/usr/bin/python3 /content/stylegan2-ada-pytorch/train.py --snap {SNAP} --outdir {EXPERIMENTS} --data {DATA}"
!{cmd}

!/usr/bin/python3 /content/stylegan2-ada-pytorch/train.py --snap 25 --resume /content/drive/MyDrive/data/gan/experiments/00007-circuit-auto1/network-snapshot-000500.pkl --outdir /content/drive/MyDrive/data/gan/experiments --data /content/drive/MyDrive/data/gan/dataset/circuit

"""# Transfer Learning

FFHQ pkl 파일을 기반으로 훈련시키고자 하는 데이터 세트를 학습시킬 수 있음.

이를 통해 빠르고 좋은 이미지 생성이 가능
"""

#!wget -P /content/drive/MyDrive/data/gan/pretrain https://nvlabs-fi-cdn.nvidia.com/stylegan2-ada-pytorch/pretrained/transfer-learning-source-nets/ffhq-res256-mirror-paper256-noaug.pkl

# RESUME = "/content/drive/MyDrive/data/gan/pretrain/ffhq-res256-mirror-paper256-noaug.pkl"
# or
RESUME = 'ffhq256'

FREEZED = 4
BATCH = 32

import os

# Modify these to suit your needs
EXPERIMENTS = "/content/drive/MyDrive/data/gan/experiments"
#NETWORK = "network-snapshot-000200.pkl"
#RESUME = os.path.join(EXPERIMENTS, "00000-circuit-auto1", NETWORK)

# If you want to shrink the set_up snapshot image grid, then change the number in training_loop.py in training dir
# gw = np.clip(1024 // training_set.image_shape[2], 2, 32)
# gh = np.clip(1024 // training_set.image_shape[1], 2, 32)

DATA = "/content/drive/MyDrive/data/gan/dataset/circuit"
SNAP = 8

# Build the command and run it
cmd = f"/usr/bin/python3 /content/stylegan2-ada-pytorch/train.py --snap {SNAP} --resume {RESUME} --outdir {EXPERIMENTS} --batch {BATCH} --data {DATA} --freezed {FREEZED}"
!{cmd}

"""# Style Mixing

Source Image(row), Reference Image(col)에 따라 Style Mixing을 진행함.

이때, style에 대한 부분을 일부 고정시킴으로써 다양한 조합을 만들어낼 수 있음.

이를 통해 reference image에 걸맞는 스타일의 이미지 변환이 가능하게 함.

"""

import os
create_dir_path = "/content/drive/MyDrive/data/gan/experiments/style_mixing_2"
os.makedirs(create_dir_path, exist_ok=True)

output_dir = create_dir_path
rows = "1,2,3,4"
cols = "7,8,9,10"
styles = "0-6"
pkl_file_path = "/content/drive/MyDrive/data/gan/experiments/00003-circuit-auto1-batch32-resumeffhq256-freezed4/network-snapshot-000384.pkl"

cmd = f"/usr/bin/python3 /content/stylegan2-ada-pytorch/style_mixing.py --outdir {output_dir} --rows {rows} --cols {cols} --styles {styles} --network {pkl_file_path}"
!{cmd}

"""style_mixing.py 파일 내 마지막을 아래와 같이 수정함으로써 다수의 결과 이미지가 중복되지 않도록 한다.

canvas.save(f'{outdir}/grid_row_{row_seeds[0]}_to_{row_seeds[-1]}_col_{col_seeds[0]}_to_{col_seeds[-1]}_style_{col_styles[0]}_to_{col_styles[-1]}.png')
"""

import numpy as np
r = ','.join(map(str, list(np.arange(21,31))))
c = ','.join(map(str, list(np.arange(31,41))))
print(r, c)

output_dir = create_dir_path

#rows = "1,2,3,4,6,7,8,9,10"
#cols = "11,12,13,14,15,16,17,18,19,20"
rows = r
cols = c
pkl_file_path = "/content/drive/MyDrive/data/gan/experiments/00003-circuit-auto1-batch32-resumeffhq256-freezed4/network-snapshot-000384.pkl"
styles = ["0", "0-1", "0-2", "0-3", "0-4", "0-5", "0-6"]

for style in styles:
  cmd = f"/usr/bin/python3 /content/stylegan2-ada-pytorch/style_mixing.py --outdir {output_dir} --rows {rows} --cols {cols} --styles {style} --network {pkl_file_path}"
  !{cmd}